import avatar from '../src/assets/images/image.jpg'
const Course =[
  {
    id:1,
    img:avatar,
    ccode: 'C01',
    title:"Accounting",
    img:avatar,
    description:"type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unch... ",
    chr:4,
    lhr:4,
  },
  {
    id:2,
    title:"Managment",
    ccode: 'C01',
    img:avatar,
    description:"type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unch... ",
    chr:4,
    lhr:4,
  },
  {
    id:3,
    title:"ICT",
    ccode: 'C01',
    img:avatar,
    description:"type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unch... ",
    chr:4,
    lhr:4,
  },
  {
    id:4,
    title:"Accounting",
    ccode: 'C01',
    img:avatar,
    description:"type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unch... ",
    chr:4,
    lhr:4,
  },
  {
    id:5,
    title:"Accounting",
    ccode: 'C01',
    img:avatar,
    description:"type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unch... ",
    chr:4,
    lhr:4,
  },
  {
    id:6,
    title:"Accounting",
    ccode: 'C01',
    img:avatar,
    description:"type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unch... ",
    chr:4,
    lhr:4,
  },
  {
    id:7,
    title:"Accounting",
    ccode: 'C01',
    img:avatar,
    description:"type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unch... ",
    chr:4,
    lhr:4,
  },
]
export default Course;